### ISSUE TITLE
#1 Condición del revés

### ISSUE THREAD

**Issue by rafacab1** [iesgrancapitan-entornos/2019-20-practica-5-github-issues-mariamm99#1]
https://github.com/iesgrancapitan-entornos/2019-20-practica-5-github-issues-mariamm99/blob/3e8cdfab26022ec1f3a305174c0b49ce92ffefb7/EjDNI.java#L34

Esta condición sería correcta si fuera un _si no_
Es decir, con añadirle una exclamación hay.

**Comment by mariamm99** [comment]
Cierto, ahora entiendo por que no entraba en el bucle. ¡Graciaas!

**Comment by rafacab1** [comment]
De nada! ;)
